project:
  type: book
  output-dir: docs
  # execute:
  #   cache: true
  #   freeze: auto

book:
  title: "Mapping Politics: Spatial Data Science for Politics"
  author: "Dr Clemens Jarnach"
  date: "10/11/2025"
  repo-url: https://github.com/clemensjarnach/mapping-politics/
  chapters:
    - index.qmd
    - results.qmd
    - methods.qmd
    - spatial-regression.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-depth: 1
    theme: cosmo
    highlight-style: atom-one
    code-block-bg: "#f0f0f0"
    code-block-border-left: "#045a8d"
    code-fold: false
    code-summary: "Code"
    code-tools: true
    code-link: true
    code-copy: true
    split-by: chapter  
    knitr:
      opts_chunk:
        out.width: 100%
        R.options:
          width: 68
  # pdf:
  #   documentclass: scrbook
  #   always_allow_html: true
  #   include-in-header:
  #     - text: |
  #         \usepackage{dcolumn}
    
pdf-engine: lualatex